default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pwtagenda_development

test:
  <<: *default
  database: pwtagenda_test

production:
  <<: *default
  database: pwtagenda_test
